language: node_js
node_js:
  - '0.12'
  - '4'
  - '5'
  - '6'
  - 'stable'

env:
  - CXX=g++-4.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libdbus-1-dev
  - sudo apt-get install -y libglib2.0-dev

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
  packages:
    - g++-4.8
    - gcc-4.8

before_script: npm install -g standard
